import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

// The loader is generated by scripts/build-serial-refinement-browser.js.
// It must load the analytics privacy guard BEFORE any decoder helper script
// (the guard wraps window.gtag with an allowlist; helpers may emit events),
// followed by the controller core and focused patches in dependency order.
const EXPECTED_SCRIPT_ORDER = [
  '/analytics-privacy-guard.js',
  '/serial-refinement-controller-core.js',
  '/serial-multicycle-year-patch.js',
  '/serial-refinement-single-candidate-patch.js',
  '/serial-refinement-model-propagation-patch.js',
];

test('generated serial refinement loader chains the privacy guard and patches in order', () => {
  const loader = fs.readFileSync('serial-refinement-controller.js', 'utf8');

  const positions = EXPECTED_SCRIPT_ORDER.map((src) => {
    const at = loader.indexOf(`"${src}"`);
    assert.notEqual(at, -1, `loader must load ${src}`);
    assert.equal(loader.indexOf(`"${src}"`, at + 1), -1, `loader must load ${src} exactly once`);
    return at;
  });

  for (let i = 1; i < positions.length; i++) {
    assert.ok(
      positions[i - 1] < positions[i],
      `${EXPECTED_SCRIPT_ORDER[i - 1]} must load before ${EXPECTED_SCRIPT_ORDER[i]}`
    );
  }

  const referenced = [...loader.matchAll(/"(\/[^\"]+\.js)"/g)].map((m) => m[1]);
  assert.deepEqual(referenced, EXPECTED_SCRIPT_ORDER, 'loader must reference exactly these scripts, in order');
});

test('generator source of truth emits the privacy guard and focused patches', () => {
  const generator = fs.readFileSync('scripts/build-serial-refinement-browser.js', 'utf8');
  for (const src of EXPECTED_SCRIPT_ORDER) {
    assert.ok(generator.includes(src), `generator template must include ${src}`);
  }
});
