import { buildUsageReport } from '../smart-lookup/provider-usage.js';

/**
 * Pure report builders for the daily Smart Lookup / quota data. Input is what
 * the read-only script fetched (usage events + the per-subject daily hash);
 * nothing here does I/O. Subjects are hashes only.
 */

export const DISTRIBUTION_BUCKETS = Object.freeze([
  ['1', 1, 1], ['2', 2, 2], ['3', 3, 3], ['4', 4, 4], ['5', 5, 5],
  ['6-10', 6, 10], ['11-25', 11, 25], ['26+', 26, Infinity],
]);

const ratio = (numerator, denominator) => (denominator > 0 ? numerator / denominator : null);

export function bucketCounts(counts) {
  const buckets = Object.fromEntries(DISTRIBUTION_BUCKETS.map(([label]) => [label, 0]));
  for (const count of counts) {
    const bucket = DISTRIBUTION_BUCKETS.find(([, min, max]) => count >= min && count <= max);
    if (bucket) buckets[bucket[0]] += 1;
  }
  return buckets;
}

/** Nearest-rank percentile of an ascending array (p in 0-100). */
export function percentile(sortedAscending, p) {
  if (!sortedAscending.length) return null;
  const rank = Math.max(1, Math.ceil((p / 100) * sortedAscending.length));
  return sortedAscending[Math.min(rank, sortedAscending.length) - 1];
}

/** Share of all AI lookups generated by the heaviest `fraction` of users (at least one user). */
export function topShare(counts, fraction) {
  const total = counts.reduce((sum, count) => sum + count, 0);
  if (!counts.length || total === 0) return null;
  const take = Math.max(1, Math.ceil(counts.length * fraction));
  const top = [...counts].sort((a, b) => b - a).slice(0, take).reduce((sum, count) => sum + count, 0);
  return top / total;
}

/**
 * Splits the daily subject hash. `anon:ip-*` subjects are visitors without a
 * usable visitor ID (blocked storage, API callers, bots); they are reported
 * separately so they do not distort the human distribution.
 */
export function splitSubjects(dailyHash = {}) {
  const groups = { visitors: [], ipFallback: [], accounts: [] };
  for (const [subject, raw] of Object.entries(dailyHash || {})) {
    const count = Number(raw);
    if (!Number.isFinite(count) || count <= 0) continue;
    if (subject.startsWith('acct:')) groups.accounts.push(count);
    else if (subject.startsWith('anon:ip-')) groups.ipFallback.push(count);
    else if (subject.startsWith('anon:')) groups.visitors.push(count);
  }
  return groups;
}

/** Conventional median: the middle value, or the mean of the two middle values for an even count. */
function median(sortedAscending) {
  const n = sortedAscending.length;
  if (!n) return null;
  const mid = Math.floor(n / 2);
  return n % 2 ? sortedAscending[mid] : (sortedAscending[mid - 1] + sortedAscending[mid]) / 2;
}

export function summarizeDistribution(counts, thresholds = []) {
  const sorted = [...counts].sort((a, b) => a - b);
  const users = sorted.length;
  const totalLookups = sorted.reduce((sum, count) => sum + count, 0);
  return {
    users,
    totalLookups,
    median: median(sorted),
    p90: percentile(sorted, 90),
    p95: percentile(sorted, 95),
    p99: percentile(sorted, 99),
    max: users ? sorted[users - 1] : null,
    buckets: bucketCounts(sorted),
    topShare: { top1: topShare(sorted, 0.01), top5: topShare(sorted, 0.05), top10: topShare(sorted, 0.1) },
    thresholds: thresholds.map((limit) => {
      const hit = sorted.filter((count) => count >= limit).length;
      const exceed = sorted.filter((count) => count > limit).length;
      const blockedLookups = sorted.reduce((sum, count) => sum + Math.max(0, count - limit), 0);
      return {
        limit,
        hit,
        hitShare: ratio(hit, users),
        exceed,
        exceedShare: ratio(exceed, users),
        blockedLookups,
        blockedLookupShare: ratio(blockedLookups, totalLookups),
      };
    }),
  };
}

export function buildSmartLookupReport({ usage, daily = {}, ipDaily = {}, config }) {
  const perRoute = buildUsageReport(usage);
  const age = perRoute.routes.find((route) => route.route === 'age') || null;
  const refine = perRoute.routes.find((route) => route.route === 'refine') || null;
  const event = (name) => usage.events[`age|${name}`] ?? 0;

  const outcomes = { local: event('outcome:local'), cache: event('outcome:cache'), deterministic: event('outcome:deterministic'), ai: event('outcome:ai'), other: event('outcome:other') };
  const totalAttempts = Object.values(outcomes).reduce((sum, value) => sum + value, 0);

  const counted = event('ai_lookup');
  const refunded = event('ai_lookup_refunded');
  const netLogical = Math.max(0, counted - refunded);
  const providerCalls = (provider) => usage.rows
    .filter((row) => row.route === 'age' && row.provider === provider)
    .reduce((sum, row) => sum + row.calls, 0);
  const ageCalls = age?.calls ?? 0;

  const groups = splitSubjects(daily);
  const anonymousLimit = config.tiers.anonymous.daily;
  const thresholds = [...new Set([anonymousLimit, 10].filter((value) => Number.isInteger(value)))].sort((a, b) => a - b);
  const distribution = summarizeDistribution(groups.visitors, thresholds);
  const ipCounts = Object.values(ipDaily || {}).map(Number).filter((count) => Number.isFinite(count) && count > 0);

  return {
    metered: totalAttempts > 0 || counted > 0 || groups.visitors.length > 0,
    traffic: {
      totalAttempts,
      outcomes,
      shares: Object.fromEntries(Object.entries(outcomes).map(([name, value]) => [name, ratio(value, totalAttempts)])),
    },
    aiUtilization: {
      logicalAiLookups: counted,
      refunded,
      duplicatesIgnored: event('ai_lookup_duplicate'),
      netLogicalAiLookups: netLogical,
      aiShareOfAttempts: ratio(outcomes.ai, totalAttempts),
      providerAttempts: ageCalls,
      byProvider: {
        gemini: providerCalls('gemini'),
        openai: providerCalls('openai'),
        xai: providerCalls('xai'),
        groq: providerCalls('groq'),
      },
      // Per logical (per-user) lookup and per provider chain that actually ran.
      attemptsPerLogicalLookup: ratio(ageCalls, netLogical),
      attemptsPerPaidChain: age?.callsPerPaidLookup ?? null,
      tokens: { input: age?.inputTokens ?? 0, output: age?.outputTokens ?? 0, thinking: age?.thinkingTokens ?? 0 },
    },
    costControl: {
      rateLimitRate: age?.rateLimitRate ?? null,
      geminiRateLimitRate: age && age.geminiCalls ? ratio(age.geminiRateLimited, age.geminiCalls) : null,
      fallbackRate: age?.fallbackRate ?? null,
      geminiCooldownSkips: event('gemini_cooldown_skip'),
      refinement: refine
        ? {
          providerCalls: refine.calls,
          paidLookups: refine.paidLookups,
          requestsCounted: refine.refineRequestsCounted,
          refinementRate: refine.refinementRate,
          rateLimitRate: refine.rateLimitRate,
        }
        : null,
    },
    users: {
      anonymousVisitors: distribution.users,
      ipFallbackSubjects: groups.ipFallback.length,
      accounts: groups.accounts.length,
      distribution,
    },
    hypotheticalQuota: {
      anonymousDailyLimit: anonymousLimit,
      thresholds: distribution.thresholds,
      wouldBlockAtLeastOnce: event('quota_would_block'),
      ipDailyLimit: config.ipDailyLimit,
      ipsOverLimit: config.ipDailyLimit === null ? 0 : ipCounts.filter((count) => count > config.ipDailyLimit).length,
      ipsSeen: ipCounts.length,
    },
  };
}
